spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/greenroof
    username: postgres
    password: abcd1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    session:
      cookie:
        same-site: strict
